import type Product from "@/Utils/Interfaces/Product.ts";

export default function getTestProducts():Product[]{
    return [
        {
            id:1,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"used",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:2,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"used",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:3,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"used",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:4,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:5,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:6,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:7,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:8,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:9,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:10,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:11,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:12,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:13,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:14,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:15,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:16,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:17,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:18,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:19,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:20,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:21,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:22,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:23,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:24,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:25,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:26,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:27,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:28,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:29,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        },
        {
            id:30,
            ownerEmail:"test@gmail.com",
            title:"Phone",
            description:"Phone sdfjhkncfkew wjfvwmeivfh oiwejfovtwmefih b owefjovwmefhv iow wefhiuvwefivuhweifhvew eowfhvowhfve",
            price:231.0,
            condition:"new",
            status:"active",
            photoFirst:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoSecond:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            photoThird:"https://d8iqbmvu05s9c.cloudfront.net/ajprhqgqg1otf7d5sm7u3brf27gv",
            createdAt:new Date().toISOString()
        }

    ]
}