spring.application.name=backend

spring.http.codecs.max-in-memory-size=200MB
spring.webflux.multipart.max-in-memory-size=100MB
spring.webflux.multipart.max-disk-usage-per-part=200MB

spring.kafka.topic=ai-messages-topic